### ISSUE TITLE
Lenovo Ideapad S145 81W800E9

### ISSUE THREAD

**Issue by dpatel** [boffik/LenovoS145-15IWL_OpenCore#1]
I am planning to buy Lenovo Ideapad S145 81W800E9IN 15.6-inch FHD Thin and Light Laptop (10th Gen i5-1035G1/8GB/512GB SSD model, does this EFI work with this model? Also, do the inbuilt wifi and Bluetooth works? Do you have any installation guide?

**Comment by boffik** [comment]
I m not sure if this EFI will help you. Bluetooth and Wifi won't work on Hackintosh - 100%.
